const mongoose = require('mongoose');

const techNewsSchema = new mongoose.Schema({
  title: { type: String, required: true, trim: true, maxlength: 300 },
  summary: { type: String, default: '', maxlength: 2000 },
  // Fun beginner Arabic explainer (cached, generated by ELNADY — not Google Translate)
  summaryAr: { type: String, default: '', maxlength: 3000 },
  url: { type: String, required: true, trim: true },
  image: { type: String, default: '' },
  source: { type: String, default: 'Tech', trim: true },
  /** world | egypt | arab */
  region: {
    type: String,
    enum: ['world', 'egypt', 'arab'],
    default: 'world',
    index: true,
  },
  category: {
    type: String,
    enum: [
      'ai',
      'frontend',
      'backend',
      'mobile',
      'releases',
      'uiux',
      'cybersecurity',
      'data',
      'automation',
      'marketing',
      'freelancing',
      'arab', // legacy — migrated to region=arab on refresh
      'general',
    ],
    default: 'general',
  },
  publishedAt: { type: Date, default: Date.now },
  // Deduplicate auto-imported items
  externalId: { type: String, default: '', index: true },
  isAuto: { type: Boolean, default: true },
  isPinned: { type: Boolean, default: false },
  isHidden: { type: Boolean, default: false },
  isActive: { type: Boolean, default: true },
  createdBy: { type: mongoose.Schema.Types.ObjectId, ref: 'User' },
}, { timestamps: true });

techNewsSchema.index({ publishedAt: -1, isPinned: -1 });
techNewsSchema.index({ region: 1, category: 1, publishedAt: -1 });
techNewsSchema.index({ url: 1 }, { unique: false });

module.exports = mongoose.model('TechNews', techNewsSchema);
